name: Nginx Static

on:
  push:
    paths:
      - 'nginx-static/*'
      - '.github/workflows/nginx-static.yml'

jobs:

  build:

    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@v1
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: whoan/docker-images/nginx-static
        registry: docker.pkg.github.com
        context: nginx-static
