name: Node Alpine Slim

on:
  push:
    paths:
      - 'node-alpine-slim/*'
      - '.github/workflows/node-alpine-slim.yml'

jobs:

  build:

    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: whoan/docker-images/node
        image_tag: alpine-slim
        registry: docker.pkg.github.com
        context: node-alpine-slim
