name: Quickfix Debian Buster

on:
  push:
    paths:
      - 'quickfix/debian-10*'
      - '.github/workflows/quickfix-debian-buster.yml'

jobs:

  build:

    name: Build docker image (with cache) and push it to registry
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: whoan/docker-images/quickfix
        image_tag: debian-buster
        registry: docker.pkg.github.com
        context: quickfix/debian-10
